export const COUNTRIES = [
  "Chile",
  "Argentina",
  "Perú",
  "Colombia",
  "México",
  "Brasil",
  "Uruguay",
  "Paraguay",
  "Bolivia",
  "Ecuador",
  "Venezuela",
  "Costa Rica",
  "Panamá",
  "República Dominicana",
  "España",
  "Estados Unidos",
] as const;

export const CITIES = [
  "Santiago",
  "Viña del Mar",
  "Valparaíso",
  "Concepción",
  "Antofagasta",
  "La Serena",
  "Temuco",
  "Buenos Aires",
  "Córdoba",
  "Lima",
  "Bogotá",
  "Medellín",
  "Ciudad de México",
  "Monterrey",
  "Guadalajara",
  "São Paulo",
  "Rio de Janeiro",
  "Montevideo",
  "Quito",
  "Madrid",
  "Barcelona",
  "Miami",
] as const;

export const INDUSTRIES = [
  "Tecnología",
  "Banca y Servicios Financieros",
  "Retail",
  "Consumo Masivo",
  "Industrial / Manufactura",
  "Minería",
  "Energía",
  "Construcción e Inmobiliaria",
  "Logística y Transporte",
  "Salud y Farma",
  "Educación",
  "Telecomunicaciones",
  "Agroindustria",
  "Servicios Profesionales",
  "Hospitality y Turismo",
  "Seguros",
  "Gobierno y Sector Público",
  "Forestal",
  "Automotriz",
] as const;

export const TARGET_ROLES = [
  "CEO / Gerente General",
  "COO / Gerente de Operaciones",
  "CFO / Gerente de Administración y Finanzas",
  "CMO / Gerente de Marketing",
  "CCO / Gerente Comercial",
  "CHRO / Gerente de Personas",
  "CTO / Gerente de Tecnología",
  "CIO / Gerente de TI",
  "Director Comercial",
  "Director de Operaciones",
  "Director de Personas",
  "Director Industrial",
  "Director de Proyectos",
  "Gerente Comercial Regional",
  "Gerente de Ventas",
  "Gerente de Marketing",
  "Gerente de Producto",
  "Gerente de Planta",
  "Head of Sales",
  "Head of Engineering",
  "Head of Product",
  "Head of Data",
  "Subgerente Comercial",
  "Subgerente de Operaciones",
  "Country Manager",
] as const;

export const WORK_MODES = ["Presencial", "Híbrido", "Remoto"] as const;

export const SENIORITIES = [
  "Trainee",
  "Junior",
  "Intermedio",
  "Semi Senior",
  "Senior",
  "Lead",
  "Manager",
  "Director",
  "VP",
  "C-Level",
] as const;

export const REPORT_TO_OPTIONS = [
  "Directorio",
  "CEO / Gerente General",
  "COO",
  "CFO",
  "CMO",
  "CCO",
  "CHRO",
  "CTO",
  "VP de área",
  "Director del área",
  "Gerente del área",
  "Comité ejecutivo",
] as const;

export const URGENCIES = ["Alta", "Media", "Baja"] as const;

export const MANDATE_STATUSES = [
  "Borrador",
  "Activo",
  "Perfil objetivo generado",
  "En evaluación de candidatos",
  "Con shortlist",
  "Cerrado",
  "Archivado",
] as const;
